# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: #/426-21-blog

# Title of the Site
title: Stat 396 - Fall 2022
# Description of the Site
description: Data Science Process
# URL of Image of the Site
site-image: /assets/images/yellow.jpg # /assets/images/logo.png
# Keywords of the Site
site-keywords: BYU, Data Science, Projects
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/yellow.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email:
facebook_username:
twitter_username:
instagram_username:
linkedin_username:
github_username:
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Stat 426 Class
# URL for the Image of the Author
author-image: /assets/images/logo.png
author-image-alt: /assets/images/yellow2.jpg #/assets/images/Stat426.png
# 60 Words About the Author
author-about: Statistics 386 is a class taught in the Statistics Department at Brigham Young University.  In this class, we cover the data science process including collecting and wrangling data, version control, exploratory data analysis, visualization, ethics and bias.  The class this semester is taught by Shannon Tass.  

author-about-small:  Data science methods and applications
author-url: https://github.com/stat386-fall2022

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
